AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

# To get fixed

Layout/LineLength:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Security/Eval:
  Enabled: false

# test_ronn_document fails when it uses safe_load
Security/YAMLLoad:
  Enabled: false

# Permanently disabled - I don't care about these.

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/WordArray:
  Enabled: false

