language: ruby

matrix:
  allow_failures:
    - rvm: jruby-9.2.7.0

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9.2.7.0

before_install:
  - gem install bundler:2.1.4

install:
  - bundle install --with development

script:
  - bundle exec rubocop
  - bundle exec rake test
  - bundle exec rake man
