language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3

before_install:
  - gem install bundler:2.0.2

install:
  - bundle install --with development

script:
  - bundle exec rake test
  - bundle exec rake package
  - bundle exec rake man
  - bundle exec rubocop
