language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem install bundler:2.0.2

install:
  - bundle install --with development

script:
  - bundle exec rake test
  - bundle exec rake package
  - bundle exec rake man
  - bundle exec rubocop
